Repository spryker/cypress-tests, pull requests merged in 2025-07, with the labels that each got.

#145 AE-212 Adjusted measurement unit gui tests to run for b2b and b2b-mp demoshops
  cypress/e2e/backoffice/product-measurement-unit/product-measurement-unit-create.cy.ts
  cypress/e2e/backoffice/product-measurement-unit/product-measurement-unit-list.cy.ts
Labels: request-review, improvement

#148 FRW-10738 Fixed Flickery E2E Tests for MFA.
  cypress/e2e/backoffice/multi-factor-authentication/user-mfa-auth.cy.ts
  cypress/e2e/mp/multi-factor-authentication/merchant-agent-mfa-auth.cy.ts
  cypress/e2e/mp/multi-factor-authentication/merchant-user-mfa-auth.cy.ts
  cypress/e2e/yves/multi-factor-authentication/agent-mfa-auth.cy.ts
  cypress/e2e/yves/multi-factor-authentication/customer-mfa-auth.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/pages/mp/multi-factor-auth/merchant-user-multi-factor-auth-repository.ts
  cypress/support/scenarios/mp/merchant-user-set-up-mfa-scenario.ts
Labels: improvement

#151 FRW-9814 Fixes for Agent Dashboard tests.
  cypress/e2e/mp/marketplace-agent-assist/agent-dashboard.cy.ts
Labels: enhancement

#164 FRW-10736 Added new test for locale switching.
  cypress/e2e/yves/core/locale-switching.cy.ts
  cypress/fixtures/b2b-mp/yves/core/static-locale-switching.json
  cypress/fixtures/b2b/yves/core/static-locale-switching.json
  cypress/fixtures/b2c-mp/yves/core/static-locale-switching.json
  cypress/fixtures/b2c/yves/core/static-locale-switching.json
  cypress/fixtures/suite/yves/core/static-locale-switching.json
  cypress/support/pages/yves/home/home-page.ts
  cypress/support/pages/yves/home/home-repository.ts
  cypress/support/pages/yves/home/repositories/b2b-home-repository.ts
  cypress/support/pages/yves/home/repositories/b2b-mp-home-repository.ts
  cypress/support/pages/yves/home/repositories/b2c-home-repository.ts
  cypress/support/pages/yves/home/repositories/b2c-mp-home-repository.ts
  cypress/support/pages/yves/home/repositories/suite-home-repository.ts
  cypress/support/types/yves/locale.ts
Labels: bug
